version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./logs:/mosquitto/log
    env_file:
      - .dockerenv
    command: >
      sh -c "
      source .dockerenv &&
      touch /mosquitto/config/pwfile &&
      chmod 700 /mosquitto/config/pwfile &&
      chown mosquitto:mosquitto /mosquitto/config/pwfile &&
      mosquitto_passwd -b /mosquitto/config/pwfile $MQTT_USER $MQTT_BROKER_PASSWORD &&
      mosquitto -c /mosquitto/config/mosquitto.conf"
    stdin_open: true
    tty: true
  
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file: .dockerenv
      
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization script to create table
    ports:
      - "5432:5432"  # Exposing the default PostgreSQL port

  wormhole:
    build: .
    container_name: wormhole
    depends_on:
      - mqtt-broker
      - postgres
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - .dockerenv
    restart: always

volumes:
  grafana-data:

networks:
  default:
    driver: bridge
