CREATE TABLE IF NOT EXISTS reading (
  id SERIAL PRIMARY KEY,
  device VARCHAR(255),
  sensor VARCHAR(255),
  reading FLOAT,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE reading ALTER COLUMN date TYPE TIMESTAMP WITH TIME ZONE;